### ISSUE TITLE
Add authentication to django

### ISSUE THREAD

**Issue by proegssilb** [proegssilb/FactorioServerManager#17]
While there are some pieces of Auth0 support in django, currently it's not known whether the integration is working. This needs to be verified as working, or replaced with something else, before we can actually limit who can see what games.

**Comment by AnnYe-Fluithaas** [comment]
This tutorial gives a good walkthrough of how to connect a django application to Auth0
https://auth0.com/docs/quickstart/webapp/django/01-login
